import 'server-only';

import { randomUUID } from 'node:crypto';
import { mkdir, readFile, unlink, writeFile } from 'node:fs/promises';
import path from 'node:path';

import type { StorageDriver } from './index';

// Files are written here, deliberately OUTSIDE the public/ folder. Anything in
// public/ is served to the whole internet by filename; resumes must only ever be
// reachable through a route handler that checks who is asking.
const UPLOAD_DIR = path.resolve(process.cwd(), process.env.UPLOAD_DIR ?? './uploads');

/**
 * Resolves a storage key to a path on disk, refusing anything that would escape
 * the upload directory.
 *
 * Keys are generated by `put`, so they are safe by construction - but a key also
 * arrives from the database, and this is the last line of defence against a
 * traversal like `../../.env` if one ever got stored.
 */
function resolveKey(key: string): string {
  const target = path.resolve(UPLOAD_DIR, key);
  const root = UPLOAD_DIR + path.sep;

  if (target !== UPLOAD_DIR && !target.startsWith(root)) {
    throw new Error('Refusing to access a path outside the upload directory.');
  }

  return target;
}

export const localStorageDriver: StorageDriver = {
  async put({ data, extension, prefix = 'resumes' }) {
    // A random name means a key cannot be guessed from someone's name or id,
    // and two people uploading "resume.pdf" never collide.
    const key = `${prefix}/${randomUUID()}${extension}`;
    const target = resolveKey(key);

    await mkdir(path.dirname(target), { recursive: true });
    await writeFile(target, data);

    return key;
  },

  async get(key) {
    try {
      return await readFile(resolveKey(key));
    } catch (error) {
      // A missing file is a normal outcome, not an error worth throwing.
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') return null;
      throw error;
    }
  },

  async remove(key) {
    try {
      await unlink(resolveKey(key));
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error;
    }
  },
};
